### ISSUE TITLE
Suggest/Request Additional Algorithms In Qiskit

### ISSUE THREAD

**Issue by aryashah2k** [QPower-Research/QPowerAlgo#24]
In addition to the already listed algorithms by @born-2learn @ricardoprins  and team, I wished to suggest the addition of certain algorithms that I could work on towards contributing to the repository's Qiskit Section.
The Algorithms that I suggest to be added and can contribute to as well are:

- [ ] QAOA - Quantum Approximate Optimization Algorithm
- [ ] QSVM - Quantum Support Vector Machine Algorithm
- [ ] VQC - Variational Quantum Classifier

Please let me know if these algorithms can be a valuable addition and if so, do consider assigning them to me. Would love working on them.

**Comment by born-2learn** [comment]
Thanks for the addition of new algorithms @aryashah2k . You can get started with QAOA and QSVM as one of us is already working on a VQC. Closing this issue as it will now be covered in #11
