### ISSUE TITLE
Add QGANs Implementation | Qiskit Algorithms

### ISSUE THREAD

**Issue by aryashah2k** [QPower-Research/QPowerAlgo#28]
@born-2learn ,Hi, I  have been working on QSVM and Came across the concept of Quantum Generative Adversarial Networks. I would love to work on that and contribute that to the Qiskit Section of Repository.

I have previously worked on QAOA (Pull request Created 😄
I shall soon create one for QSVM

If it will be of value to the repo then please consider addition of QGANs and assign the issue to me

Please Tag the issue under DWOC

**Comment by born-2learn** [comment]
Sure @aryashah2k, you can work on QGANs with qiskit. It will indeed be of great value to QPowerAlgo.
