### ISSUE TITLE
Add Discrete Time and Continuous Time Quantum Random Walk Algorithms | Qiskit

### ISSUE THREAD

**Issue by aryashah2k** [QPower-Research/QPowerAlgo#34]
@born-2learn @ricardoprins  I have a prior issue yet to be assigned #28 
Also I have Two Pending Pull Requests #30 #27 .

Apart form the above stated works. I would like to work on Discrete Time and Continuous Time Quantum Random Walks with implementations in Qiskit.

Do assign me this issue and review my pending PRs to the earliest.

Regards,
Arya.

**Comment by aryashah2k** [comment]
@ricardoprins @born-2learn Thanks for assigning the issue. Any Updates on my pending PRs #30 #27 and Issue #28 ?

**Comment by born-2learn** [comment]
@aryashah2k your pending PRs have been approved and merged to master.

**Comment by aryashah2k** [comment]
@born-2learn , Do I create a Separate Folder for Continuous and Discrete Walks or do I add both in a single folder?
Also, Do I create a separate issue for each algorithm(Continuous and Discrete Walks) under DWOC? Since Both are different Algorithms? Do let me know so that I proceed accordingly!
