### ISSUE TITLE
Add Bernstein Vazirani Algorithm Implementation In Q# [QSharp]

### ISSUE THREAD

**Issue by aryashah2k** [QPower-Research/QPowerAlgo#39]
@born-2learn , @ricardoprins I wish to add code implementation for the  algorithm in Q# . The Q# Directory is pretty empty as of now and during my time at DWOC I feel like I should contribute towards Q# as well apart form Qiskit where I have PRs merged and issues created.

**Comment by mar-galho** [comment]
Sure, go ahead!

**Comment by aryashah2k** [comment]
Thanks, please add the dwoc label to this issue and add levels to my previous merged PRs.

Also please merge my current PRs as well...

**Comment by aryashah2k** [comment]
@ricardoprins @born-2learn , please make sure to merge this PR by today (25th Feb) since it marks the last day of DWOC. I shall continue being associated with this community even after the event ends but for my scores to reflect on leaderboard, I request you to merge them with appropriate labels by today!!
